import { useCallback, useEffect, useRef, useState } from 'react';
import {
  ActionIcon, Badge, Box, Button, Divider, Group, Loader, Modal, Paper,
  SimpleGrid, Stack, Table, Tabs, Text, TextInput, ThemeIcon, Title, Tooltip,
} from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { notifications } from '@mantine/notifications';
import {
  LuPlus, LuTrash2, LuDownload, LuPencil, LuCheck, LuX, LuTable,
  LuSparkles, LuChartBar, LuCircleCheck, LuActivity, LuFile, LuFileText,
  LuRefreshCw,
} from 'react-icons/lu';
import jsPDF from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, ImageRun } from 'docx';
import { useAppSelector } from '../../../Redux/hooks';
import {
  fetchResultTables, createResultTable, saveResultTable, deleteResultTable,
} from '../../../supabase/resultTables';
import type { DBResultTable } from '../../../supabase/resultTables';
import { fetchAIReport, saveAIReport } from '../../../supabase/aiReports';
import {
  generateEngineJSON, isEngineConfigured, AIEngineError,
} from '../../../helper/aiEngines';
import cognitaLogo from '../../../assets/cognita-logo.png';

// ── Types ─────────────────────────────────────────────────────────────────────

interface ResultFinding {
  title:   string;
  content: string;
}

interface ResultAnalysis {
  tableName:      string;
  generatedAt:    string;
  summary:        string;
  findings:       ResultFinding[];
  recommendations: string[];
  tableSnapshot:  { headers: string[]; rows: string[][] };
}

function isValidAnalysis(v: unknown): v is ResultAnalysis {
  if (!v || typeof v !== 'object') return false;
  const r = v as Record<string, unknown>;
  return typeof r.summary === 'string' && Array.isArray(r.findings) && Array.isArray(r.recommendations);
}

// ── Prompt builder ────────────────────────────────────────────────────────────

function buildPrompt(table: DBResultTable): string {
  const sample = table.rows.slice(0, 10);
  const tableText = [table.headers, ...sample]
    .map(r => r.join(' | '))
    .join('\n');
  return `You are an expert academic data analyst helping a student interpret their research results table.

TABLE NAME: "${table.name}"
COLUMNS (${table.headers.length}): ${table.headers.join(', ')}
DATA (${sample.length} of ${table.rows.length} rows):
${tableText}

Analyse the data in this table and provide:
- A clear executive summary of the key patterns and insights
- 4-6 key findings with specific, detailed explanations referencing the data
- 3-5 actionable recommendations for the researcher

Respond ONLY in this exact JSON (no markdown fences, no extra text):
{"summary":"...","findings":[{"title":"...","content":"..."}],"recommendations":["..."]}`;
}

// ── PDF download ──────────────────────────────────────────────────────────────

async function downloadPDF(analysis: ResultAnalysis) {
  const doc     = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW   = doc.internal.pageSize.getWidth();
  const pageH   = doc.internal.pageSize.getHeight();
  const margin  = 18;
  const contentW = pageW - margin * 2;

  const logoImg = await new Promise<HTMLImageElement>((resolve, reject) => {
    const img = new Image();
    img.onload  = () => resolve(img);
    img.onerror = reject;
    img.src = cognitaLogo;
  });

  // Faint watermark
  try {
    doc.saveGraphicsState();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (doc as any).setGState(new (doc as any).GState({ opacity: 0.06 }));
    doc.addImage(logoImg, 'PNG', (pageW - 110) / 2, (pageH - 55) / 2, 110, 55);
    doc.restoreGraphicsState();
  } catch { /* watermark is decorative */ }

  // Header bar
  doc.setFillColor(59, 91, 219);
  doc.rect(0, 0, pageW, 26, 'F');
  doc.addImage(logoImg, 'PNG', margin, 3, 28, 18);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Results Analysis Report', pageW - margin, 13, { align: 'right' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Generated by Cognita AI · ${new Date(analysis.generatedAt).toLocaleDateString()}`,
    pageW - margin, 20, { align: 'right' },
  );

  let y = 36;

  // Title
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(analysis.tableName, margin, y);
  y += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(110, 110, 110);
  doc.text(
    `AI-Powered Result Analysis · ${new Date(analysis.generatedAt).toLocaleString()}`,
    margin, y,
  );
  y += 5;

  doc.setDrawColor(59, 91, 219);
  doc.setLineWidth(0.4);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // Summary
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', margin, y);
  y += 6;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(55, 55, 55);
  const sumLines = doc.splitTextToSize(analysis.summary, contentW);
  doc.text(sumLines, margin, y);
  y += sumLines.length * 5 + 8;

  // Data table snapshot
  if (analysis.tableSnapshot?.headers?.length) {
    if (y > pageH - 50) { doc.addPage(); y = 18; }
    doc.setTextColor(20, 20, 20);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Data Table', margin, y);
    y += 6;

    const snap    = analysis.tableSnapshot;
    const colW    = Math.min(contentW / snap.headers.length, 45);
    const rowsToShow = snap.rows.slice(0, 8);

    // Header row
    doc.setFillColor(59, 91, 219);
    doc.rect(margin, y - 4, contentW, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    snap.headers.forEach((h, i) => {
      doc.text(String(h).slice(0, 14), margin + i * colW + 2, y + 1);
    });
    y += 8;

    // Data rows
    rowsToShow.forEach((row, ri) => {
      if (y > pageH - 18) return;
      doc.setFillColor(ri % 2 === 0 ? 248 : 255, ri % 2 === 0 ? 249 : 255, ri % 2 === 0 ? 250 : 255);
      doc.rect(margin, y - 4, contentW, 7, 'F');
      doc.setTextColor(55, 55, 55);
      doc.setFont('helvetica', 'normal');
      row.forEach((cell, ci) => {
        doc.text(String(cell).slice(0, 14), margin + ci * colW + 2, y + 1);
      });
      y += 7;
    });
    if (snap.rows.length > 8) {
      doc.setFontSize(7);
      doc.setTextColor(130, 130, 130);
      doc.text(`…showing 8 of ${snap.rows.length} rows`, margin, y + 3);
      y += 7;
    }
    y += 6;
  }

  // Key Findings
  if (y > pageH - 40) { doc.addPage(); y = 18; }
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Key Findings', margin, y);
  y += 7;

  for (let i = 0; i < analysis.findings.length; i++) {
    const f = analysis.findings[i];
    const bodyLines = doc.splitTextToSize(f.content, contentW - 6);
    const blockH    = 14 + bodyLines.length * 5;
    if (y + blockH > pageH - 22) { doc.addPage(); y = 18; }

    doc.setFillColor(245, 247, 255);
    doc.roundedRect(margin, y - 4, contentW, blockH, 2, 2, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(59, 91, 219);
    doc.text(`${i + 1}. ${f.title}`, margin + 4, y + 2);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(55, 55, 55);
    doc.text(bodyLines, margin + 4, y);
    y += bodyLines.length * 5 + 7;
  }

  // Recommendations
  if (y > pageH - 40) { doc.addPage(); y = 18; }
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Recommendations', margin, y);
  y += 7;
  for (const rec of analysis.recommendations) {
    if (y > pageH - 18) { doc.addPage(); y = 18; }
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(55, 55, 55);
    const recLines = doc.splitTextToSize(`• ${rec}`, contentW);
    doc.text(recLines, margin, y);
    y += recLines.length * 5 + 3;
  }

  // Footer
  doc.setFillColor(245, 247, 255);
  doc.rect(0, pageH - 9, pageW, 9, 'F');
  doc.setFontSize(7);
  doc.setTextColor(130, 130, 130);
  doc.text('Powered by Cognita AI · Research Analysis Platform', pageW / 2, pageH - 2.5, { align: 'center' });

  doc.save(`${analysis.tableName.replace(/\s+/g, '_')}_Results_Analysis.pdf`);
}

// ── DOCX download ─────────────────────────────────────────────────────────────

async function downloadDOCX(analysis: ResultAnalysis) {
  const logoResp   = await fetch(cognitaLogo);
  const logoBuffer = await logoResp.arrayBuffer();

  const docFile = new Document({
    sections: [{
      children: [
        new Paragraph({
          children: [
            new ImageRun({
              data: logoBuffer,
              transformation: { width: 130, height: 52 },
              type: 'png',
            }),
          ],
        }),
        new Paragraph({ text: '' }),
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun({ text: analysis.tableName, bold: true, color: '3B5BDB' })],
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: `Results Analysis · Generated ${new Date(analysis.generatedAt).toLocaleString()}`,
              color: '888888',
              size: 18,
            }),
          ],
        }),
        new Paragraph({ text: '' }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: 'Executive Summary', bold: true })],
        }),
        new Paragraph({ children: [new TextRun({ text: analysis.summary })] }),
        new Paragraph({ text: '' }),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: 'Key Findings', bold: true })],
        }),
        ...analysis.findings.flatMap((f, i) => [
          new Paragraph({
            heading: HeadingLevel.HEADING_3,
            children: [new TextRun({ text: `${i + 1}. ${f.title}`, bold: true, color: '3B5BDB' })],
          }),
          new Paragraph({ children: [new TextRun({ text: f.content })] }),
          new Paragraph({ text: '' }),
        ]),
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: 'Recommendations', bold: true })],
        }),
        ...analysis.recommendations.map(rec =>
          new Paragraph({ children: [new TextRun({ text: `• ${rec}` })] }),
        ),
        new Paragraph({ text: '' }),
        new Paragraph({
          children: [
            new TextRun({
              text: 'Powered by Cognita AI · Research Analysis Platform',
              color: 'AAAAAA',
              size: 16,
            }),
          ],
        }),
      ],
    }],
  });

  const blob = await Packer.toBlob(docFile);
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `${analysis.tableName.replace(/\s+/g, '_')}_Results_Analysis.docx`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── CSV export ────────────────────────────────────────────────────────────────

function exportCSV(table: DBResultTable) {
  const rows = [table.headers, ...table.rows];
  const csv  = rows.map(r => r.map(c => `"${c.replace(/"/g, '""')}"`).join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: `${table.name}.csv` });
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Cell input ────────────────────────────────────────────────────────────────

function Cell({
  value, onChange, isHeader = false, placeholder = '',
}: {
  value: string; onChange: (v: string) => void;
  isHeader?: boolean; placeholder?: string;
}) {
  return (
    <Box
      component="input"
      value={value}
      onChange={(e: React.ChangeEvent<HTMLInputElement>) => onChange(e.currentTarget.value)}
      placeholder={placeholder}
      style={{
        width: '100%', minWidth: 100, border: 'none', outline: 'none',
        background: 'transparent', fontSize: 13,
        fontWeight: isHeader ? 700 : 400,
        color: isHeader ? '#1c2840' : '#343a40',
        padding: '6px 8px', fontFamily: 'inherit',
      }}
    />
  );
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function StudentResults() {
  const user = useAppSelector(s => s.auth.user);

  // Table state
  const [tables,        setTables]        = useState<DBResultTable[]>([]);
  const [loading,       setLoading]       = useState(true);
  const [activeId,      setActiveId]      = useState<string | null>(null);
  const [hoveredRow,    setHoveredRow]    = useState<number | null>(null);
  const [hoveredCol,    setHoveredCol]    = useState<number | null>(null);
  const [renamingTable, setRenamingTable] = useState(false);
  const [renameVal,     setRenameVal]     = useState('');
  const [newTableOpen,  { open: openNewTable, close: closeNewTable }] = useDisclosure(false);
  const [newName,       setNewName]       = useState('');
  const [creating,      setCreating]      = useState(false);

  // Tabs
  const [activeTab, setActiveTab] = useState<string | null>('tables');

  // AI analysis state
  const [analysisRunning,  setAnalysisRunning]  = useState(false);
  const [analysis,         setAnalysis]         = useState<ResultAnalysis | null>(null);
  const [analysisTableId,  setAnalysisTableId]  = useState<string | null>(null);
  const [downloading,      setDownloading]      = useState<'pdf' | 'docx' | null>(null);

  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const active = tables.find(t => t.id === activeId) ?? null;

  // ── Load ────────────────────────────────────────────────────────────────────
  useEffect(() => {
    if (!user?.id) { setLoading(false); return; }
    Promise.all([
      fetchResultTables(user.id),
      fetchAIReport<ResultAnalysis>(user.id, 'analysis'),
    ]).then(([rows, reportRow]) => {
      setTables(rows);
      if (rows.length) {
        setActiveId(rows[0].id);
        setAnalysisTableId(rows[0].id);
      }
      if (reportRow?.data && isValidAnalysis(reportRow.data)) setAnalysis(reportRow.data);
    }).finally(() => setLoading(false));
  }, [user?.id]);

  // ── Debounced save ───────────────────────────────────────────────────────────
  const scheduleSave = useCallback((id: string, patch: Partial<Pick<DBResultTable, 'name' | 'headers' | 'rows'>>) => {
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => saveResultTable(id, patch), 800);
  }, []);

  const mutate = useCallback((id: string, updater: (t: DBResultTable) => DBResultTable) => {
    setTables(prev => prev.map(t => {
      if (t.id !== id) return t;
      const next = updater(t);
      scheduleSave(id, { name: next.name, headers: next.headers, rows: next.rows });
      return next;
    }));
  }, [scheduleSave]);

  const updateCell   = (row: number, col: number, val: string) => activeId && mutate(activeId, t => ({ ...t, rows: t.rows.map((r, ri) => ri === row ? r.map((c, ci) => ci === col ? val : c) : r) }));
  const updateHeader = (col: number, val: string)              => activeId && mutate(activeId, t => ({ ...t, headers: t.headers.map((h, i) => i === col ? val : h) }));
  const addRow       = () => activeId && active && mutate(activeId, t => ({ ...t, rows: [...t.rows, Array(t.headers.length).fill('')] }));
  const addColumn    = () => activeId && active && mutate(activeId, t => ({ ...t, headers: [...t.headers, `Column ${t.headers.length + 1}`], rows: t.rows.map(r => [...r, '']) }));
  const deleteRow    = (row: number) => activeId && mutate(activeId, t => ({ ...t, rows: t.rows.filter((_, i) => i !== row) }));
  const deleteColumn = (col: number) => activeId && mutate(activeId, t => ({ ...t, headers: t.headers.filter((_, i) => i !== col), rows: t.rows.map(r => r.filter((_, i) => i !== col)) }));

  const renameTable = () => {
    if (!activeId || !renameVal.trim()) return;
    mutate(activeId, t => ({ ...t, name: renameVal.trim() }));
    setRenamingTable(false);
  };

  const handleCreate = async () => {
    if (!newName.trim() || !user?.id) return;
    setCreating(true);
    const created = await createResultTable(user.id, user.institutionId ?? '', newName.trim());
    if (created) {
      setTables(prev => [...prev, created]);
      setActiveId(created.id);
      setAnalysisTableId(created.id);
      notifications.show({ message: `Table "${created.name}" created.`, color: 'teal' });
      closeNewTable();
      setNewName('');
    } else {
      notifications.show({ title: 'Could not create table', message: 'Run the SQL setup in Supabase first.', color: 'red' });
    }
    setCreating(false);
  };

  const handleDeleteTable = async (id: string) => {
    await deleteResultTable(id);
    setTables(prev => {
      const next = prev.filter(t => t.id !== id);
      setActiveId(next.length ? next[0].id : null);
      setAnalysisTableId(next.length ? next[0].id : null);
      return next;
    });
    notifications.show({ message: 'Table deleted.', color: 'red' });
  };

  // ── Run AI analysis ─────────────────────────────────────────────────────────
  async function handleRunAnalysis() {
    const table = tables.find(t => t.id === analysisTableId);
    if (!table) {
      notifications.show({ title: 'No table selected', message: 'Select a result table to analyse.', color: 'orange' });
      return;
    }
    if (!isEngineConfigured('claude')) {
      notifications.show({ title: 'Claude not configured', message: 'Add VITE_CLAUDE_API_KEY to your .env file.', color: 'red' });
      return;
    }
    if (table.rows.length === 0 || table.rows.every(r => r.every(c => !c.trim()))) {
      notifications.show({ title: 'Empty table', message: 'Add some data to the table before running analysis.', color: 'orange' });
      return;
    }

    setAnalysisRunning(true);
    setActiveTab('analysis');
    try {
      const prompt = buildPrompt(table);
      const raw    = await generateEngineJSON<{ summary: string; findings: ResultFinding[]; recommendations: string[] }>(prompt, 'claude');
      if (!isValidAnalysis(raw)) throw new AIEngineError('Unexpected response shape.');

      const result: ResultAnalysis = {
        tableName:       table.name,
        generatedAt:     new Date().toISOString(),
        summary:         raw.summary,
        findings:        raw.findings,
        recommendations: raw.recommendations,
        tableSnapshot:   { headers: table.headers, rows: table.rows },
      };
      setAnalysis(result);
      if (user?.id) await saveAIReport(user.id, 'analysis', result);
      notifications.show({ title: 'Analysis complete', message: 'Results are ready in the Analysis tab.', color: 'green' });
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Analysis failed.';
      notifications.show({ title: 'Analysis failed', message: msg, color: 'red' });
      setActiveTab('tables');
    } finally {
      setAnalysisRunning(false);
    }
  }

  // ── Download ────────────────────────────────────────────────────────────────
  async function handleDownload(fmt: 'pdf' | 'docx') {
    if (!analysis) return;
    setDownloading(fmt);
    try {
      if (fmt === 'pdf') await downloadPDF(analysis);
      else               await downloadDOCX(analysis);
    } catch {
      notifications.show({ title: 'Download failed', message: 'Could not generate the file.', color: 'red' });
    } finally {
      setDownloading(null);
    }
  }

  // ── Render ─────────────────────────────────────────────────────────────────

  if (loading) return <Box p="xl" ta="center"><Loader color="brand" /></Box>;

  return (
    <Box p="xl">
      <Group justify="space-between" align="flex-start" mb="xl">
        <Box>
          <Title order={2}>Results Builder</Title>
          <Text size="sm" c="dimmed" mt={4}>
            Create and edit result tables, then run AI-powered analysis and download your report.
          </Text>
        </Box>
        <Group gap="xs">
          {tables.length > 0 && isEngineConfigured('claude') && (
            <Button
              variant="light"
              color="brand"
              leftSection={analysisRunning ? <Loader size={13} color="currentColor" /> : <LuSparkles size={14} />}
              loading={analysisRunning}
              onClick={handleRunAnalysis}
            >
              Analyse with AI
            </Button>
          )}
          <Button leftSection={<LuPlus size={16} />} color="brand" onClick={openNewTable}>
            New Table
          </Button>
        </Group>
      </Group>

      <Tabs value={activeTab} onChange={setActiveTab}>
        <Tabs.List mb="xl">
          <Tabs.Tab value="tables"   leftSection={<LuTable    size={15} />}>Tables</Tabs.Tab>
          <Tabs.Tab value="analysis" leftSection={<LuChartBar size={15} />}
            rightSection={analysis ? <LuCircleCheck size={12} color="#2f9e44" /> : undefined}>
            AI Analysis
          </Tabs.Tab>
        </Tabs.List>

        {/* ══════════ TABLES TAB ══════════ */}
        <Tabs.Panel value="tables">
          {tables.length === 0 ? (
            <Paper withBorder radius="md" p="xl" ta="center">
              <LuTable size={40} color="#ced4da" style={{ margin: '0 auto 12px' }} />
              <Text fw={600} mb={4}>No result tables yet</Text>
              <Text size="sm" c="dimmed" mb="md">Click "New Table" to create your first results table.</Text>
              <Button leftSection={<LuPlus size={14} />} color="brand" onClick={openNewTable}>New Table</Button>
            </Paper>
          ) : (
            <Group align="flex-start" gap="md" wrap="nowrap">

              {/* Sidebar */}
              <Paper withBorder p="md" radius="md" style={{ width: 220, flexShrink: 0 }}>
                <Text size="xs" fw={700} c="dimmed" mb="sm" style={{ letterSpacing: '0.05em' }}>TABLES</Text>
                <Stack gap={4}>
                  {tables.map(t => (
                    <Group key={t.id} gap={4} wrap="nowrap"
                      style={{
                        borderRadius: 8, padding: '6px 8px', cursor: 'pointer',
                        background: activeId === t.id ? '#eef2ff' : 'transparent',
                        borderLeft: activeId === t.id ? '3px solid #3b5bdb' : '3px solid transparent',
                      }}
                      onClick={() => { setActiveId(t.id); setAnalysisTableId(t.id); }}
                    >
                      <LuTable size={13} color={activeId === t.id ? '#3b5bdb' : '#adb5bd'} style={{ flexShrink: 0 }} />
                      <Text size="xs" fw={activeId === t.id ? 600 : 400} truncate
                        style={{ flex: 1, color: activeId === t.id ? '#3b5bdb' : '#495057' }}>
                        {t.name}
                      </Text>
                      <ActionIcon size="xs" variant="subtle" color="red"
                        onClick={e => { e.stopPropagation(); handleDeleteTable(t.id); }}>
                        <LuTrash2 size={11} />
                      </ActionIcon>
                    </Group>
                  ))}
                </Stack>
              </Paper>

              {/* Editor */}
              {active && (
                <Paper withBorder radius="md" style={{ flex: 1, overflow: 'hidden' }}>
                  {/* Toolbar */}
                  <Group justify="space-between" px="md" py="sm"
                    style={{ borderBottom: '1px solid #f1f3f5' }}>
                    <Group gap="xs">
                      {renamingTable ? (
                        <Group gap="xs">
                          <TextInput size="xs" value={renameVal}
                            onChange={e => setRenameVal(e.currentTarget.value)}
                            onKeyDown={e => { if (e.key === 'Enter') renameTable(); if (e.key === 'Escape') setRenamingTable(false); }}
                            style={{ width: 200 }} autoFocus />
                          <ActionIcon size="sm" color="brand" variant="light" onClick={renameTable}><LuCheck size={13} /></ActionIcon>
                          <ActionIcon size="sm" color="gray" variant="light" onClick={() => setRenamingTable(false)}><LuX size={13} /></ActionIcon>
                        </Group>
                      ) : (
                        <Group gap={6}>
                          <Text fw={600} size="sm">{active.name}</Text>
                          <ActionIcon size="xs" variant="subtle" color="gray"
                            onClick={() => { setRenameVal(active.name); setRenamingTable(true); }}>
                            <LuPencil size={12} />
                          </ActionIcon>
                        </Group>
                      )}
                      <Text size="xs" c="dimmed">
                        {active.rows.length} rows · {active.headers.length} columns
                      </Text>
                    </Group>
                    <Group gap="xs">
                      <Button size="xs" variant="light" leftSection={<LuPlus size={12} />} onClick={addRow}>Add Row</Button>
                      <Button size="xs" variant="light" leftSection={<LuPlus size={12} />} onClick={addColumn}>Add Column</Button>
                      <Tooltip label="Export CSV" withArrow>
                        <ActionIcon size="sm" variant="light" color="brand" onClick={() => exportCSV(active)}>
                          <LuDownload size={14} />
                        </ActionIcon>
                      </Tooltip>
                      {isEngineConfigured('claude') && (
                        <Tooltip label="Analyse with AI" withArrow>
                          <ActionIcon size="sm" variant="light" color="violet"
                            loading={analysisRunning}
                            onClick={handleRunAnalysis}>
                            <LuSparkles size={14} />
                          </ActionIcon>
                        </Tooltip>
                      )}
                    </Group>
                  </Group>

                  {/* Editable table */}
                  <Box style={{ overflowX: 'auto', overflowY: 'auto', maxHeight: 'calc(100vh - 300px)' }}>
                    <table style={{ width: '100%', borderCollapse: 'collapse', tableLayout: 'auto' }}>
                      <thead>
                        <tr style={{ background: '#f8f9fa', borderBottom: '2px solid #dee2e6' }}>
                          <th style={{ width: 40, padding: '6px 8px', borderRight: '1px solid #dee2e6', color: '#adb5bd', fontSize: 12 }}>#</th>
                          {active.headers.map((h, ci) => (
                            <th key={ci}
                              style={{ borderRight: ci < active.headers.length - 1 ? '1px solid #dee2e6' : undefined, position: 'relative', minWidth: 120 }}
                              onMouseEnter={() => setHoveredCol(ci)}
                              onMouseLeave={() => setHoveredCol(null)}
                            >
                              <Group gap={2} wrap="nowrap">
                                <Cell value={h} onChange={v => updateHeader(ci, v)} isHeader placeholder={`Column ${ci + 1}`} />
                                {hoveredCol === ci && active.headers.length > 1 && (
                                  <ActionIcon size="xs" variant="subtle" color="red" style={{ flexShrink: 0, marginRight: 4 }}
                                    onClick={() => deleteColumn(ci)}>
                                    <LuX size={11} />
                                  </ActionIcon>
                                )}
                              </Group>
                            </th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {active.rows.map((row, ri) => (
                          <tr key={ri}
                            style={{ borderBottom: '1px solid #f1f3f5', background: hoveredRow === ri ? '#f8f9ff' : 'white' }}
                            onMouseEnter={() => setHoveredRow(ri)}
                            onMouseLeave={() => setHoveredRow(null)}
                          >
                            <td style={{ width: 40, padding: '0 8px', borderRight: '1px solid #f1f3f5', textAlign: 'center' }}>
                              {hoveredRow === ri && active.rows.length > 1 ? (
                                <ActionIcon size="xs" variant="subtle" color="red" onClick={() => deleteRow(ri)}>
                                  <LuX size={11} />
                                </ActionIcon>
                              ) : (
                                <Text size="xs" c="dimmed">{ri + 1}</Text>
                              )}
                            </td>
                            {row.map((cell, ci) => (
                              <td key={ci}
                                style={{ borderRight: ci < row.length - 1 ? '1px solid #f1f3f5' : undefined }}>
                                <Cell value={cell} onChange={v => updateCell(ri, ci, v)} placeholder="—" />
                              </td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </Box>
                </Paper>
              )}
            </Group>
          )}

          {/* AI call-to-action banner */}
          {tables.length > 0 && isEngineConfigured('claude') && (
            <Paper withBorder radius="md" p="md" mt="xl"
              style={{ background: 'linear-gradient(135deg, #f0f4ff 0%, #e8f5e9 100%)', borderColor: '#3b5bdb' }}>
              <Group gap="sm" wrap="wrap">
                <ThemeIcon size={36} radius="md" color="brand" variant="light">
                  <LuSparkles size={18} />
                </ThemeIcon>
                <Box style={{ flex: 1 }}>
                  <Text fw={700} size="sm">AI-Powered Result Analysis</Text>
                  <Text size="xs" c="dimmed">
                    Let Claude analyse your selected table and generate a full report with findings, recommendations, and downloadable PDF/DOCX.
                  </Text>
                </Box>
                <Button size="sm" color="brand"
                  leftSection={analysisRunning ? <Loader size={12} color="white" /> : <LuSparkles size={13} />}
                  loading={analysisRunning}
                  onClick={handleRunAnalysis}>
                  Run Analysis
                </Button>
              </Group>
            </Paper>
          )}

          {tables.length > 0 && !isEngineConfigured('claude') && (
            <Paper withBorder radius="md" p="md" mt="xl" style={{ borderColor: '#fd7e14' }}>
              <Group gap="sm">
                <ThemeIcon size={32} radius="md" color="orange" variant="light">
                  <LuSparkles size={16} />
                </ThemeIcon>
                <Text size="sm" c="orange">
                  Add <strong>VITE_CLAUDE_API_KEY</strong> to your <code>.env</code> file to enable AI-powered analysis of your result tables.
                </Text>
              </Group>
            </Paper>
          )}
        </Tabs.Panel>

        {/* ══════════ AI ANALYSIS TAB ══════════ */}
        <Tabs.Panel value="analysis">
          {!analysis && !analysisRunning ? (
            <Paper withBorder p="xl" radius="md" ta="center" bg="white">
              <ThemeIcon size={52} radius="xl" color="gray" variant="light" mx="auto" mb="md">
                <LuChartBar size={24} />
              </ThemeIcon>
              <Text fw={600} mb={4}>No analysis yet</Text>
              <Text size="sm" c="dimmed" mb="md">
                Go to the Tables tab, enter your data, and click "Analyse with AI".
              </Text>
              <Button variant="light" color="brand" leftSection={<LuActivity size={14} />}
                onClick={() => setActiveTab('tables')}>
                Go to Tables
              </Button>
            </Paper>
          ) : analysisRunning ? (
            <Paper withBorder p="xl" radius="md" ta="center" bg="white">
              <Loader size={40} color="brand" mx="auto" mb="md" />
              <Text fw={600}>Analysing your results…</Text>
              <Text size="sm" c="dimmed" mt={4}>Claude is reading your table and generating insights. This may take a moment.</Text>
            </Paper>
          ) : analysis && (
            <Stack gap="lg">

              {/* ── 1. Report header ── */}
              <Paper withBorder radius="md" style={{ overflow: 'hidden' }}>
                {/* Blue top bar */}
                <Box px="xl" py="md" style={{ background: '#3b5bdb' }}>
                  <Group justify="space-between" align="center" wrap="wrap" gap="sm">
                    <Group gap="sm" align="center">
                      <img src={cognitaLogo} alt="Cognita" style={{ height: 26, filter: 'brightness(0) invert(1)' }} />
                      <Divider orientation="vertical" color="rgba(255,255,255,0.3)" />
                      <Box>
                        <Text fw={700} size="md" style={{ color: 'white' }}>{analysis.tableName}</Text>
                        <Text size="xs" style={{ color: 'rgba(255,255,255,0.75)' }}>Results Analysis Report</Text>
                      </Box>
                    </Group>
                    <Group gap="xs">
                      <Badge size="sm" variant="light" style={{ background: 'rgba(255,255,255,0.15)', color: 'white', border: '1px solid rgba(255,255,255,0.25)' }}>
                        Claude 3.5 Sonnet
                      </Badge>
                      <Text size="xs" style={{ color: 'rgba(255,255,255,0.7)' }}>
                        Generated {new Date(analysis.generatedAt).toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
                      </Text>
                    </Group>
                  </Group>
                </Box>

                {/* Action bar */}
                <Box px="xl" py="sm" style={{ background: '#f8f9ff', borderBottom: '1px solid #e9ecef' }}>
                  <Group justify="space-between" wrap="wrap" gap="xs">
                    <Group gap={6}>
                      <LuCircleCheck size={14} color="#2f9e44" />
                      <Text size="xs" c="dimmed">
                        {analysis.findings.length} finding{analysis.findings.length !== 1 ? 's' : ''} · {analysis.recommendations.length} recommendation{analysis.recommendations.length !== 1 ? 's' : ''}
                      </Text>
                    </Group>
                    <Group gap="xs">
                      <Button size="xs" variant="light" color="red"
                        leftSection={downloading === 'pdf' ? <Loader size={11} color="currentColor" /> : <LuFile size={12} />}
                        loading={downloading === 'pdf'}
                        onClick={() => handleDownload('pdf')}>
                        PDF
                      </Button>
                      <Button size="xs" variant="light" color="blue"
                        leftSection={downloading === 'docx' ? <Loader size={11} color="currentColor" /> : <LuFileText size={12} />}
                        loading={downloading === 'docx'}
                        onClick={() => handleDownload('docx')}>
                        DOCX
                      </Button>
                      <Button size="xs" variant="subtle" color="gray"
                        leftSection={<LuRefreshCw size={11} />}
                        onClick={handleRunAnalysis}
                        loading={analysisRunning}>
                        Re-run
                      </Button>
                    </Group>
                  </Group>
                </Box>
              </Paper>

              {/* ── 2. Metric tiles ── */}
              <SimpleGrid cols={{ base: 2, sm: 4 }} spacing="sm">
                {[
                  { label: 'Key Findings',      value: analysis.findings.length,        color: '#3b5bdb', bg: '#f0f4ff' },
                  { label: 'Recommendations',   value: analysis.recommendations.length, color: '#2f9e44', bg: '#f0fdf4' },
                  { label: 'Data Rows',         value: analysis.tableSnapshot?.rows?.length ?? 0, color: '#f08c00', bg: '#fff8f0' },
                  { label: 'Columns Analysed',  value: analysis.tableSnapshot?.headers?.length ?? 0, color: '#7c3aed', bg: '#f5f0ff' },
                ].map(({ label, value, color, bg }) => (
                  <Paper key={label} withBorder p="md" radius="md" style={{ background: bg, borderColor: color + '30' }}>
                    <Text style={{ fontSize: 32, fontWeight: 800, lineHeight: 1, color }}>{value}</Text>
                    <Text size="xs" c="dimmed" mt={4} fw={500}>{label}</Text>
                  </Paper>
                ))}
              </SimpleGrid>

              {/* ── 3. Executive Summary ── */}
              <Paper withBorder p="xl" radius="md" bg="white">
                <Group gap="sm" mb="md">
                  <ThemeIcon size={32} radius="md" color="brand" variant="light">
                    <LuChartBar size={16} />
                  </ThemeIcon>
                  <Box>
                    <Text fw={700} size="sm">Executive Summary</Text>
                    <Text size="xs" c="dimmed">AI-generated overview of key patterns and insights</Text>
                  </Box>
                </Group>
                <Divider mb="md" />
                <Box p="md" style={{ background: '#f8f9ff', borderRadius: 8, borderLeft: '4px solid #3b5bdb' }}>
                  <Text size="sm" style={{ lineHeight: 1.7 }}>{analysis.summary}</Text>
                </Box>
              </Paper>

              {/* ── 4. Data Table Snapshot ── */}
              {analysis.tableSnapshot?.headers?.length > 0 && (
                <Paper withBorder p="xl" radius="md" bg="white">
                  <Group gap="sm" mb="md">
                    <ThemeIcon size={32} radius="md" color="teal" variant="light">
                      <LuTable size={16} />
                    </ThemeIcon>
                    <Box>
                      <Text fw={700} size="sm">Data Table — {analysis.tableName}</Text>
                      <Text size="xs" c="dimmed">
                        {analysis.tableSnapshot.rows.length > 10
                          ? `Showing 10 of ${analysis.tableSnapshot.rows.length} rows`
                          : `${analysis.tableSnapshot.rows.length} row${analysis.tableSnapshot.rows.length !== 1 ? 's' : ''}`}
                      </Text>
                    </Box>
                  </Group>
                  <Divider mb="md" />
                  <Box style={{ overflowX: 'auto' }}>
                    <Table striped highlightOnHover withTableBorder withColumnBorders>
                      <Table.Thead style={{ background: '#3b5bdb' }}>
                        <Table.Tr>
                          {analysis.tableSnapshot.headers.map((h, i) => (
                            <Table.Th key={i} style={{ color: 'white', fontWeight: 700, fontSize: 12 }}>{h}</Table.Th>
                          ))}
                        </Table.Tr>
                      </Table.Thead>
                      <Table.Tbody>
                        {analysis.tableSnapshot.rows.slice(0, 10).map((row, ri) => (
                          <Table.Tr key={ri}>
                            {row.map((cell, ci) => (
                              <Table.Td key={ci}>
                                <Text size="sm">{cell || <Text span c="dimmed" size="xs">—</Text>}</Text>
                              </Table.Td>
                            ))}
                          </Table.Tr>
                        ))}
                      </Table.Tbody>
                    </Table>
                  </Box>
                </Paper>
              )}

              {/* ── 5. Key Findings ── */}
              <Paper withBorder p="xl" radius="md" bg="white">
                <Group gap="sm" mb="md">
                  <ThemeIcon size={32} radius="md" color="brand" variant="light">
                    <LuSparkles size={16} />
                  </ThemeIcon>
                  <Box>
                    <Text fw={700} size="sm">Key Findings</Text>
                    <Text size="xs" c="dimmed">{analysis.findings.length} finding{analysis.findings.length !== 1 ? 's' : ''} identified from the data</Text>
                  </Box>
                </Group>
                <Divider mb="md" />
                <Stack gap="sm">
                  {analysis.findings.map((f, i) => (
                    <Box key={i} p="md" style={{ border: '1px solid #e9ecef', borderRadius: 8, background: '#f8f9ff' }}>
                      <Group gap="sm" align="flex-start" wrap="nowrap">
                        <Box style={{
                          flexShrink: 0, width: 28, height: 28, borderRadius: '50%',
                          background: '#3b5bdb', display: 'flex', alignItems: 'center', justifyContent: 'center',
                        }}>
                          <Text size="xs" fw={800} style={{ color: 'white' }}>{i + 1}</Text>
                        </Box>
                        <Box style={{ flex: 1 }}>
                          <Text size="sm" fw={600} mb={4} style={{ color: '#1c2840' }}>{f.title}</Text>
                          <Text size="sm" c="dimmed" style={{ lineHeight: 1.6 }}>{f.content}</Text>
                        </Box>
                      </Group>
                    </Box>
                  ))}
                </Stack>
              </Paper>

              {/* ── 6. Recommendations ── */}
              <Paper withBorder p="xl" radius="md" bg="white">
                <Group gap="sm" mb="md">
                  <ThemeIcon size={32} radius="md" color="green" variant="light">
                    <LuCircleCheck size={16} />
                  </ThemeIcon>
                  <Box>
                    <Text fw={700} size="sm">Recommendations</Text>
                    <Text size="xs" c="dimmed">{analysis.recommendations.length} actionable recommendation{analysis.recommendations.length !== 1 ? 's' : ''}</Text>
                  </Box>
                </Group>
                <Divider mb="md" />
                <Stack gap="xs">
                  {analysis.recommendations.map((rec, i) => (
                    <Group key={i} gap="sm" align="flex-start" wrap="nowrap" p="sm"
                      style={{ border: '1px solid #e9ecef', borderRadius: 8, background: '#f0fdf4' }}>
                      <Box style={{
                        flexShrink: 0, width: 22, height: 22, borderRadius: '50%',
                        background: '#2f9e44', display: 'flex', alignItems: 'center', justifyContent: 'center', marginTop: 1,
                      }}>
                        <Text size="10px" fw={800} style={{ color: 'white' }}>{i + 1}</Text>
                      </Box>
                      <Text size="sm" style={{ lineHeight: 1.6 }}>{rec}</Text>
                    </Group>
                  ))}
                </Stack>
              </Paper>

              {/* ── 7. Footer ── */}
              <Paper withBorder p="md" radius="md" style={{ background: '#f8f9fa' }}>
                <Group justify="space-between" wrap="wrap" gap="xs">
                  <Group gap="xs">
                    <img src={cognitaLogo} alt="Cognita" style={{ height: 18, opacity: 0.5 }} />
                    <Text size="xs" c="dimmed">Powered by Cognita AI · Research Analysis Platform</Text>
                  </Group>
                  <Group gap="xs">
                    <Button size="xs" color="red" variant="light"
                      leftSection={downloading === 'pdf' ? <Loader size={11} color="currentColor" /> : <LuFile size={12} />}
                      loading={downloading === 'pdf'}
                      onClick={() => handleDownload('pdf')}>
                      Download PDF
                    </Button>
                    <Button size="xs" color="blue" variant="light"
                      leftSection={downloading === 'docx' ? <Loader size={11} color="currentColor" /> : <LuFileText size={12} />}
                      loading={downloading === 'docx'}
                      onClick={() => handleDownload('docx')}>
                      Download DOCX
                    </Button>
                  </Group>
                </Group>
              </Paper>

            </Stack>
          )}
        </Tabs.Panel>
      </Tabs>

      {/* New table modal */}
      <Modal opened={newTableOpen} onClose={closeNewTable} title="Create New Table" size="sm">
        <Stack gap="md">
          <TextInput label="Table name" placeholder="e.g. Table 1: Model Accuracy Comparison"
            value={newName} onChange={e => setNewName(e.currentTarget.value)}
            onKeyDown={e => e.key === 'Enter' && handleCreate()} autoFocus />
          <Button color="brand" loading={creating} disabled={!newName.trim()} onClick={handleCreate}>
            Create Table
          </Button>
        </Stack>
      </Modal>
    </Box>
  );
}
